info:
  app:
    name: main-service
# настройки для переноса в конфиг
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform=org:
      hibernate:
        dialect: PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        entitymanager:
          factory:
            interface: jakarta.persistence.EntityManagerFactory
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/main-db
    username: dbuser
    password: 12345

logging:
  level:
    ru.practicum.stats: INFO
    #    org.springframework.web: INFO
    #    org.springframework.validation: INFO
    org.springframework.transaction.interceptor: TRACE

server:
  port: 0

management:
  endpoints.web.exposure.include: health