info:
  app:
    name: collector

kafka:
  value-serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  bootstrap-server: localhost:9092
  topics:
    user-action-topic: stats.user-actions.v1

grpc:
  server:
    port: 0 #59091

logging:
  level:
    ru.yandex.practicum: DEBUG
    org.springframework.cloud.netflix.eureka: INFO
    apache.kafka: WARN
    io.grpc: INFO

management:
  endpoints.web.exposure.include: health,info
