info:
  app:
    name: stats-client

stats:
  server:
    name: stats-server  # имя сервиса в Eureka
    url: http://localhost:9090  # fallback url
    endpoints:
      hit: /hit
      stats: /stats
  retry:
    enabled: true
    max-attempts: 3
    initial-interval: 1000
    multiplier: 2.0
    max-interval: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true