#spring:
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
#    username: ${db.user}
#    password: ${db.password}
#    sql.init.mode: always
#
#server:
#  port: 0 # TODO чтобы прошли тесты и не получать динамический адрес можно использовать хард порт 9090
#
#logging:
#  level:
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#
#db:
#  name: ewm_stats_db
#  host: localhost
#  port: 5432
#  user: dbuser
#  password: 12345

info:
  app:
    name: stats-server
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform=org:
      hibernate:
        dialect: PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        entitymanager:
          factory:
            interface: jakarta.persistence.EntityManagerFactory
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stats-db
    username: dbuser
    password: 12345

logging:
  level:
    ru.practicum.stats: INFO
    org.springframework.transaction.interceptor: TRACE

server:
  port: 9090
#TODO 0 - переделать на дисковери клиент

management:
  endpoints.web.exposure.include: health