spring:
  application:
    name: event-service
  cloud:
    discovery:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    database-platform=org:
      hibernate:
        dialect: PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        entitymanager:
          factory:
            interface: jakarta.persistence.EntityManagerFactory
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/event_service
    username: dbuser
    password: 12345

logging:
  level:
    ru.practicum.stats: INFO
    org.springframework.transaction.interceptor: TRACE

server:
  port: 0

grpc:
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

management:
  endpoints.web.exposure.include: health,info